name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        working-directory: backend
        run: npm install --force

      - name: Deploy Smart Contract
        working-directory: backend
        env:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          SEPOLIA_PRIVATE_KEY: ${{ secrets.SEPOLIA_PRIVATE_KEY }}
        run: |
          npm run deploy

      - name: Commit and push changes
        continue-on-error: true
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update abi files and .env from deployment"
          git push origin main --force

  deploy-frontend:
    needs: deploy-backend
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install and Build 🔧
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/build
